In [ ]:
#Q1
import numpy as np
arr = np.array([1 , 2 , 3 , 4 , 5])
add_arr = arr + 2
mult_arr = arr * 3
div_arr = arr / 2
print("Original:", arr)
print("Added:", add_arr)
print("Multiplied:",mult_arr)
print("Divided:",div_arr)

Original: [1 2 3 4 5]
Added: [3 4 5 6 7]
Multiplied: [ 3  6  9 12 15]
Divided: [0.5 1.  1.5 2.  2.5]


In [ ]:
#Q2
arr = np.array([1,2,3,6,4,5])
print(arr[::-1])

[5 4 6 3 2 1]


In [ ]:
#q2
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
elems,counts = np.unique(x,return_counts=True)
print(elems)
print(counts)
print(f'Element with the most occurence:{elems[np.argmax(counts)]}')
elemsY,countsY = np.unique(y,return_counts=True)
print(elemsY)
print(countsY)
print(f'Element with the most occurence:{elemsY[np.argmax(countsY)]}')

[1 2 3 4 5]
[5 2 1 1 1]
Element with the most occurence:1
[1 2 3 4]
[3 2 3 2]
Element with the most occurence:1


In [ ]:
#Q3
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [12]:
#Q4
Kumud = np.linspace(10,100,25)
print("Dimensions:",Kumud.ndim)
print("Shape:",Kumud.shape)
print("Size:",Kumud.size)
print("Data Type:",Kumud.dtype)
print("Total Bytes:",Kumud.nbytes)
transposed_array = Kumud.reshape(5,5)
print("Using T attribute (Does not work for 1D array):",Kumud.T)

Dimensions: 1
Shape: (25,)
Size: 25
Data Type: float64
Total Bytes: 200
Using T attribute (Does not work for 1D array): [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [13]:
#Q5
ucs420_Kumud = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
mean_value = np.mean(ucs420_Kumud)
print(mean_value)
median_value = np.median(ucs420_Kumud)
print(median_value)
max_value = np.max(ucs420_Kumud)
print(max_value)
min_value = np.min(ucs420_Kumud)
print(min_value)
unique_values = np.unique(ucs420_Kumud)
print(unique_values)
reshaped_ucs420 = ucs420_Kumud.reshape(4,3)
print(reshaped_ucs420)
resized_ucs420 = np.resize(ucs420_Kumud,(2,3))
print(resized_ucs420)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
